environment:
  NODEJS_VERSION: "stable"

image:
  - Visual Studio 2022

install:
- ps: >-
    Install-Product node $env:NODEJS_VERSION

    choco install GoogleChrome

    choco install Firefox

- cmd: >-
    npm install

build: off

test_script:
- cmd: >-
    npm test